### ISSUE TITLE
ValueError: tzinfo.utcoffset() returned 1440 on certain badly parsed datetimes

### ISSUE THREAD

**Issue by npdoty** [datactive/bigbang#290]
I get this error when trying to compute the activity frame for a handful of the IETF mailing lists. It appears that what happens is some datetime is parsed incorrectly (since emails often have incorrectly formatted date strings) and one of the datetimes is getting parsed in such a way as to have a large UTC offset, more than a day. Then later, when pandas is using a hashtable to calculate duplicates, or alternatively when pandas is serializing some data to write out to CSV, a datetime library throws this ValueError.

```
Traceback (most recent call last):
  File "bin/mail_to_activity.py", line 42, in main
    activity = bigbang.archive.Archive(archives).get_activity()
  File "/Users/nick/code/mailing-list-analysis/bigbang/bigbang/archive.py", line 64, in __init__
    self.data.drop_duplicates(inplace=True)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3535, in drop_duplicates
    duplicated = self.duplicated(subset, keep=keep)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3582, in duplicated
    labels, shape = map(list, zip(*map(f, vals)))
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3570, in f
    vals, size_hint=min(len(self), _SIZE_HINT_LIMIT))
  File "/usr/local/lib/python2.7/site-packages/pandas/core/algorithms.py", line 471, in factorize
    labels = table.get_labels(values, uniques, 0, na_sentinel, check_nulls)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1367, in pandas._libs.hashtable.PyObjectHashTable.get_labels
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
```

Another project running into this error diagnoses [some cases where this can happen, specifically with too long subsecond strings](https://github.com/crsmithdev/arrow/issues/354). But I think the more cogent issue is just that we shouldn't have a hard crash in a hard to track down way, but instead force the timezones to a correct format at some point while parsing.

**Comment by npdoty** [comment]
It's also thrown in `sort_values`(I wrapped the de-dup in try/catch):

```
Traceback (most recent call last):
  File "bin/mail_to_activity.py", line 42, in main
    activity = bigbang.archive.Archive(archives).get_activity()
  File "/Users/nick/code/mailing-list-analysis/bigbang/bigbang/archive.py", line 87, in __init__
    self.data.sort_values(by='Date', inplace=True)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3634, in sort_values
    na_position=na_position)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/sorting.py", line 250, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
```

**Comment by npdoty** [comment]
Have a proposed fix for this here: https://github.com/npdoty/bigbang/commit/885e4f4428085a5669f38c3501b1954f6836294d

I specifically try to trigger the error, and drop all the rows that have it.

**Comment by nllz** [comment]
Fixed by Nicks commit! \o/
