### ISSUE TITLE
tzdata error upon import

### ISSUE THREAD

**Issue by nllz** [datactive/bigbang#312]
There is a timezone issue while importing mailbox files. This cause the collect_mail.py command to fail, same holds true for the listcsv.py script.

The problem can be found in bigman.mailman.open_list_archives, but it seems an upstream issue with pandas.

This issue I had while importing https://www.ietf.org/mail-archive/text/ietf/

```
Traceback (most recent call last):
  File "bigbang/listcsv.py", line 6, in <module>
    mm.open_list_archives(subdirectory).to_csv(path+subdirectory+'.csv',encoding='utf-8')
  File "/home/lem/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 1524, in to_csv
    formatter.save()
  File "/home/lem/.local/lib/python2.7/site-packages/pandas/io/formats/format.py", line 1652, in save
    self._save()
  File "/home/lem/.local/lib/python2.7/site-packages/pandas/io/formats/format.py", line 1754, in _save
    self._save_chunk(start_i, end_i)
  File "/home/lem/.local/lib/python2.7/site-packages/pandas/io/formats/format.py", line 1780, in _save_chunk
    lib.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas/_libs/lib.pyx", line 1035, in pandas._libs.lib.write_csv_rows
  File "/home/lem/.local/lib/python2.7/site-packages/pandas/io/common.py", line 550, in writerows
    else pprint_thing(x).encode("utf-8") for x in row]
  File "/home/lem/.local/lib/python2.7/site-packages/pandas/io/formats/printing.py", line 230, in pprint_thing
    result = as_escaped_unicode(thing)
  File "/home/lem/.local/lib/python2.7/site-packages/pandas/io/formats/printing.py", line 193, in as_escaped_unicode
    result = compat.text_type(thing)  # we should try this first
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439

```

Am getting this issue in quite a few IETF lists, so would be nice if we could find a fix.

**Comment by nllz** [comment]
When using collect_mail.py this seems fatal, not so much for the liscsv.py script.

**Comment by sbenthall** [comment]
If I'm not mistaken, that link points to an archive with every IETF email since 1990, and it includes some files that are not in .mail format. It is difficult to debug this problem given such a broad case.

Is it possible for you to isolate the problem to:

- A smaller example that shows the problem, and
- A specific set of steps needed to reproduce the error?

Thanks.

**Comment by sbenthall** [comment]
This looks like a duplicate of #290 to me

**Comment by davidberra** [comment]
we decided to just drop the messages that generate the error

**Comment by nllz** [comment]
npdoty/bigbang@885e4f4
