### ISSUE TITLE
Error when running collect_mail on IETF lists / decimal.InvalidOperation: Invalid literal for Decimal: u' '

### ISSUE THREAD

**Issue by nllz** [datactive/bigbang#314]
Traceback (most recent call last):
  File "bin/collect_mail.py", line 54, in <module>
    main(args)
  File "bin/collect_mail.py", line 51, in main
    mailman.collect_from_file(args.f, notes=notes)
  File "/home/lem/Data/bigbang/bigbang/mailman.py", line 125, in collect_from_file
    collect_from_url(url, archive_dir=archive_dir, notes=notes)
  File "/home/lem/Data/bigbang/bigbang/mailman.py", line 97, in collect_from_url
    data = open_list_archives(url)
  File "/home/lem/Data/bigbang/bigbang/mailman.py", line 367, in open_list_archives
    return messages_to_dataframe(messages)
  File "/home/lem/Data/bigbang/bigbang/mailman.py", line 452, in messages_to_dataframe
    for m in messages if m.get('Message-ID')]
  File "/home/lem/Data/bigbang/bigbang/parse.py", line 91, in get_date
    date = dp.parse(ds)
  File "/home/lem/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 1301, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/lem/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 604, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/lem/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 701, in _parse
    i = self._parse_numeric_token(l, i, info, ymd, res, fuzzy)
  File "/home/lem/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 898, in _parse_numeric_token
    value = Decimal(tokens[idx + 2])  # TODO: try/except for this?
  File "/home/lem/Data/anaconda2/envs/bigbang/lib/python2.7/decimal.py", line 547, in __new__
    "Invalid literal for Decimal: %r" % value)
  File "/home/lem/Data/anaconda2/envs/bigbang/lib/python2.7/decimal.py", line 3872, in _raise_error
    raise error(explanation)
decimal.InvalidOperation: Invalid literal for Decimal: u' '

**Comment by nllz** [comment]
A recent one:

```
Date parsing error on: 
Wed, 31 Aug 2005 16:59:17 -0-200
unknown-8bit unknown encoding in message <sO913.GR34.7gv0.9RY4IBR3R1y@localhost>, using UTF-8 instead
Traceback (most recent call last):
  File "bin/collect_mail.py", line 54, in <module>
    main(args)
  File "bin/collect_mail.py", line 51, in main
    mailman.collect_from_file(args.f, notes=notes)
  File "/home/lem/Data/bigbang/bigbang/mailman.py", line 125, in collect_from_file
    collect_from_url(url, archive_dir=archive_dir, notes=notes)
  File "/home/lem/Data/bigbang/bigbang/mailman.py", line 97, in collect_from_url
    data = open_list_archives(url)
  File "/home/lem/Data/bigbang/bigbang/mailman.py", line 367, in open_list_archives
    return messages_to_dataframe(messages)
  File "/home/lem/Data/bigbang/bigbang/mailman.py", line 455, in messages_to_dataframe
    for m in messages if m.get('From')]
  File "/home/lem/Data/bigbang/bigbang/parse.py", line 92, in get_date
    date = dp.parse(ds)
  File "/home/lem/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 1301, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/lem/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 604, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/lem/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 701, in _parse
    i = self._parse_numeric_token(l, i, info, ymd, res, fuzzy)
  File "/home/lem/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 898, in _parse_numeric_token
    value = Decimal(tokens[idx + 2])  # TODO: try/except for this?
  File "/home/lem/Data/anaconda2/envs/bigbang/lib/python2.7/decimal.py", line 547, in __new__
    "Invalid literal for Decimal: %r" % value)
  File "/home/lem/Data/anaconda2/envs/bigbang/lib/python2.7/decimal.py", line 3872, in _raise_error
    raise error(explanation)
decimal.InvalidOperation: Invalid literal for Decimal: u' '

```
This could be the message that triggered it, but am not sure the error abt the message with ID <sO913.GR34.7gv0.9RY4IBR3R1y@localhost> was actually what crashed it. 

```
\00




From ldap-dir-bounces@ietf.org Sat Mar 04 18:20:22 2006
Received: from [127.0.0.1] (helo=stiedprmman1.va.neustar.com)
	by megatron.ietf.org with esmtp (Exim 4.43)
	id 1FFg2w-0007gw-AW; Sat, 04 Mar 2006 18:20:22 -0500
Received: from [10.91.34.44] (helo=ietf-mx.ietf.org)
	by megatron.ietf.org with esmtp (Exim 4.43) id 1FFg2v-0007gg-9g
	for ldap-dir@ietf.org; Sat, 04 Mar 2006 18:20:21 -0500
Received: from d1-53.dialup.ukrhub.net ([212.90.161.53] helo=39A008E8)
	by ietf-mx.ietf.org with smtp (Exim 4.43) id 1FFg2o-0001Mf-NN
	for ldap-dir@ietf.org; Sat, 04 Mar 2006 18:20:21 -0500
Received: from mailgate.bagman.net (HELO localhost)
	by barbless.acriflavine.fr (8.8.5) with ESMTP id w12GjIah7j10l
Received: mta63.assignat.net (smap@localhost)
	by mail.biophilous.co.jp (8.8.5/8.7.2) id K035.CZ57.7fv0A8
	for <callower@aught.co.uk>; Sun, 05 Mar 2006 03:17:13 +0400
Date: Sat, 04 Mar 2006 19:18:13 -0400
From: "Phipps" <punkrockstarljhx@yahoo.de>
To: ldap-dir@ietf.org
Message-ID: <sO913.GR34.7gv0.9RY4IBR3R1y@localhost>
MIME-Version: 1.0
Content-Type: text/plain; charset=unknown-8bit
Content-Transfer-Encoding: quoted-printable
Priority: normal
X-Spam-Score: 0.0 (/)
X-Scan-Signature: 0bc60ec82efc80c84b8d02f4b0e4de22
Subject: [Ldap-dir] Re:
X-BeenThere: ldap-dir@ietf.org
X-Mailman-Version: 2.1.5
Precedence: list
List-Id: LDAP Directorate <ldap-dir.ietf.org>
List-Unsubscribe: <https://www1.ietf.org/mailman/listinfo/ldap-dir>,
	<mailto:ldap-dir-request@ietf.org?subject=unsubscribe>
List-Post: <mailto:ldap-dir@ietf.org>
List-Help: <mailto:ldap-dir-request@ietf.org?subject=help>
List-Subscribe: <https://www1.ietf.org/mailman/listinfo/ldap-dir>,
	<mailto:ldap-dir-request@ietf.org?subject=subscribe>
Errors-To: ldap-dir-bounces@ietf.org

Hey,

FaST shipping, L0wwwW Pr!#CeSs and Toll-free customer supp0rt!

Quick        0n1!ne          C0nsu1t@t!0n.

=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D

copy the address below and paste in a your web browser:

blanketmaking.coralstrategy.com

=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D


And nigh at hand, only a very little above,=20.
Up through the darkness,.
My wife is asleep beside me..
They were luminescent without having form or light..
Hath been=97most familiar bird=97.

Thanks Alot,

Chris Yazzie

_______________________________________________
Ldap-dir mailing list
Ldap-dir@ietf.org
https://www1.ietf.org/mailman/listinfo/ldap-dir



```

**Comment by nllz** [comment]
Actually not sure it is the email above, but I get this issue with these lists, so relatively easy to reproduce:

https://ietf.org/mail-archive/text/eap/
https://ietf.org/mail-archive/text/ips/
https://ietf.org/mail-archive/text/calsch/
https://ietf.org/mail-archive/text/ldap-dir/
https://ietf.org/mail-archive/text/opes/

**Comment by npdoty** [comment]
@nllz is this still a problem, or has this been fixed with some of the better error handling on collect_mail?

**Comment by nllz** [comment]
Fixed - thanks a lot
