### ISSUE TITLE
handling non-ascii characters in email addresses when scraping archives

### ISSUE THREAD

**Issue by npdoty** [datactive/bigbang#395]
While it's uncommon, it is possible that some mailing list archives will include addresses with non-ASCII characters in the local part, or non-ASCII characters in the domain part that haven't already been converted to punycode.

Many built-in Python methods will just crash on encountering these (*sigh*).

Django has some nice functionality to try to convert them in as unmessy a way as possible, but that would be a lot to import. In the short term, we might just `email.header.Header(address).encode()` the address for the purposes of From headers.

**Comment by npdoty** [comment]
Crash looks like this when crawling a W3C mailing list archive with an address that has non-ASCII characters:

```
Traceback (most recent call last):
  File "bin/collect_mail.py", line 54, in <module>
    main(args)
  File "bin/collect_mail.py", line 49, in main
    mailman.collect_from_file(args.f, archive_dir=args.archives, notes=notes)
  File "/home/npdoty/mailing-list-analysis/bigbang/bigbang/mailman.py", line 142, in collect_from_file
    collect_from_url(url, archive_dir=archive_dir, notes=notes)
  File "/home/npdoty/mailing-list-analysis/bigbang/bigbang/mailman.py", line 90, in collect_from_url
    has_archives = collect_archive_from_url(url, archive_dir=archive_dir, notes=notes)
  File "/home/npdoty/mailing-list-analysis/bigbang/bigbang/mailman.py", line 246, in collect_archive_from_url
    return w3crawl.collect_from_url(url, archive_dir, notes=notes)
  File "/home/npdoty/mailing-list-analysis/bigbang/bigbang/w3crawl.py", line 177, in collect_from_url
    message = W3cMailingListArchivesParser().parsestr(html)
  File "/home/npdoty/mailing-list-analysis/bigbang/bigbang/w3crawl.py", line 45, in parsestr
    from_addr = email.utils.formataddr((from_name, from_address))
  File "/usr/lib64/python3.7/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)

**Comment by npdoty** [comment]
For future reference, Django has a nice function `sanitize_address` that does this a little more carefully:
https://docs.djangoproject.com/en/3.0/_modules/django/core/mail/message/

**Comment by npdoty** [comment]
I think this was fixed as of the change integrated in March https://github.com/datactive/bigbang/pull/381

But if we want to keep something open to try to test for this bug in non-W3C lists, we could open another issue to investigate.
